const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    GET_ALL_STORY_FOR_SEARCH: 'GET_ALL_STORY_FOR_SEARCH',

    GET_STORIES: 'GET_STORIES',
    GET_STORIES_LIMIT: 'GET_STORIES_LIMIT',

    GET_GENRE_DETAILS: 'GET_GENRE_DETAILS',
    GET_STORIES_BY_GENRE: 'GET_STORIES_BY_GENRE',
    
    GET_STORY_BY_ID: 'GET_STORY_BY_ID',
    GET_CHAPTER_BY_STORY_ID: 'GET_CHAPTER_BY_STORY_ID',

    GET_CHAPTER_DETAIL_BY_CHAPTER_ID: 'GET_CHAPTER_DETAIL_BY_CHAPTER_ID',

    GET_STORY_STATUS_FULL: 'GET_STORY_STATUS_FULL',
    GET_STORY_STATUS_NOT_FULL: 'GET_STORY_STATUS_NOT_FULL',


}

export default actionTypes