const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    GET_STORIES: 'GET_STORIES',
    GET_STORIES_LIMIT: 'GET_STORIES_LIMIT',

    GET_GENRE_DETAILS: 'GET_GENRE_DETAILS'
    
}

export default actionTypes